package demo.casemanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CaseResponce implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CASERESPONCE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "CASERESPONCE_ID_GENERATOR", sequenceName = "CASERESPONCE_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "reason")
   private java.lang.String reason;

   @org.kie.api.definition.type.Label(value = "state")
   private java.lang.String state;

   @org.kie.api.definition.type.Label(value = "comment")
   private java.lang.String comment;

   public CaseResponce()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public CaseResponce(java.lang.Long id, java.lang.String reason,
         java.lang.String state, java.lang.String comment)
   {
      this.id = id;
      this.reason = reason;
      this.state = state;
      this.comment = comment;
   }

}