package demo.casemanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Chargeback implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CHARGEBACK_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "CHARGEBACK_ID_GENERATOR", sequenceName = "CHARGEBACK_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "amount")
   private int amount;

   @org.kie.api.definition.type.Label(value = "reasonCode")
   private java.lang.String reasonCode;

   public Chargeback()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public int getAmount()
   {
      return this.amount;
   }

   public void setAmount(int amount)
   {
      this.amount = amount;
   }

   public java.lang.String getReasonCode()
   {
      return this.reasonCode;
   }

   public void setReasonCode(java.lang.String reasonCode)
   {
      this.reasonCode = reasonCode;
   }

   public Chargeback(java.lang.Long id, int amount, java.lang.String reasonCode)
   {
      this.id = id;
      this.amount = amount;
      this.reasonCode = reasonCode;
   }

}